### PR TITLE
Fix-103: New setting to show categories on front page course cards.

### PR DESCRIPTION
**Pull request by michael-milette**
This addresses the feature request described in #103 .

### CODE REVIEW

**Comment by rmady** [comment]
Thank you @michael-milette, you are the guy!

Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
You're welcome. Thank you for integrating the changes.

**Comment by michael-milette** [comment]
Thanks Rodrigo!

**Comment by michael-milette** [comment]
Hi @rmady ,

This new feature did not make it into the version 4.0 of Trema. Could you please add it in?

Best regards,

Michael

**Pull request merged**
